server:
  port: 8081

spring:
  application:
    name: gep-consumer

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${server.port}
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka/
